/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.repeated.word;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {


        String repeated = "I need to change my life ,but my life did not need that";
        System.out.println(repeatedWord(repeated));
    }


    public static String  repeatedWord(String repeatedWords){
        HashMap<String,Integer> newArray = new HashMap<>();

        String returnData = null;

        String[] arrayOfWords = repeatedWords.split(" ");


        for (int i = 0; i < arrayOfWords.length; i++) {

            if (arrayOfWords[i].contains(",")){
                arrayOfWords[i] = deleteComaFromString(arrayOfWords[i]);
            }


            if (newArray.containsKey(arrayOfWords[i].toLowerCase())){

                returnData = arrayOfWords[i];
                break;

            }else{
                newArray.put(arrayOfWords[i].toLowerCase(),i);
            }
        }
        return returnData;
    }




    public static String deleteComaFromString(String string){
        string = string.substring(0, string.length() - 1);
        return string;
    }
}

