/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Insertion.Sort;

import java.util.Arrays;

public class App {


    public static void main(String[] args) {


        int[] arrayForTest = {8,4,23,42,16,15};

        System.out.println(Arrays.toString(insertionSort(arrayForTest)));

    }
    public static int[] insertionSort(int[] array){
        for (int i = 1; i < array.length; i++) {
            int j = i-1;
            int key = array[i];

            while (j>=0 && key<array[j]){
                array[j+1] = array[j];
                j--;
            }
            array[j+1] = key;
        }
        return array;
    }





}
