/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void linkedlistinsert(){
        LinkedList linkedList = new LinkedList();
        assertEquals(null,linkedList.head ,"test the initial value of the head in the linked list without insert value");

        linkedList.insert(4);
        assertEquals(4,linkedList.head.val ,"test the initial value of the head in the linked list after insert value");

    }

    @Test void linkedlistincludes() {
        LinkedList<Integer> linkedList = new LinkedList<Integer>();
        linkedList.insert(1);
        linkedList.insert(4);
        linkedList.insert(10);
        linkedList.insert(3);
        linkedList.insert(2);
        linkedList.insert(11);
        linkedList.insert(21);

        assertTrue(linkedList.includes(11));
        assertFalse(linkedList.includes(5));

    }

    @Test void linkedlistoString(){
        LinkedList<Integer> linkedList = new LinkedList<Integer>();
        linkedList.insert(1);
        linkedList.insert(4);
        linkedList.insert(10);
        linkedList.insert(3);
        linkedList.insert(2);
        linkedList.insert(11);
        linkedList.insert(21);


        assertEquals(21,linkedList.head.val);
        assertEquals("{ 21 } -> { 11 } -> { 2 } -> { 3 } -> { 10 } -> { 4 } -> { 1 } -> NULL",linkedList.toString());


    }
}
