/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;
import java.util.Arrays;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());




        HashTable<Object> hash = new HashTable<>(10);

        hash.add("mosa", "this is mosa");

        System.out.println(hash.get("h"));

        System.out.println(hash.contains("ih"));


        System.out.println(hash.hash("hi"));



    }
}
