/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        LinkedList<String> linkedList = new LinkedList<String>();
        linkedList.insert("a");
        linkedList.insert("b");
        linkedList.insert("c");
        System.out.println( linkedList.includes("b"));
        System.out.println( linkedList.includes("z"));
        System.out.println( linkedList.toString());




    }
}
