/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        LinkedList<String> linkedList = new LinkedList<String>();
        linkedList.insert("a");
        linkedList.insert("b");
        linkedList.insert("c");
        System.out.println( linkedList.includes("b"));
        System.out.println( linkedList.includes("z"));
        System.out.println( linkedList.toString());
        linkedList.append("5");
linkedList.insertBefore("5","4");
        System.out.println( linkedList.toString());
linkedList.insertAfter("a","3");
        System.out.println( linkedList.toString());

        System.out.println(linkedList.kthFromEnd(2));
    }

}
